name: Render test

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: CMake
      run: cmake CMakeLists.txt
    - name: Make
      run: cmake CMakeLists.txt & make
    - name: Run
      run: ./rt
    - name: Check
      run: test -r result.png && echo "Result generated" || (echo "Result not generated!" & exit 1)
    - name: Clean
      run: make clean-all
